FROM python:3.10-slim

WORKDIR /code

RUN apt-get update && apt-get install -y \
    libgeos-dev \
    build-essential \
    default-jre-headless \
    && rm -rf /var/lib/apt/lists/*

COPY deployments/nebulastream/api/config/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt