FROM python:3.10-slim

WORKDIR /code

# System dependencies
RUN apt-get update && apt-get install -y \
    libgeos-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


CMD ["sh", "-c", "ACTIVE_ADAPTER=ksqldb uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]